spring:
  application:
    # Never use '_' in application name, both in application.yaml and pom.xml
    # Use '-' instead
    # Otherwise gateway may not work correctly
    name: producer-example

  # Message queue
  cloud:
    stream:
      kafka:
        binder:
          # 9092 is the default port of Kafka
          brokers: localhost:9092
      bindings:
        # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.html
        # Format: <method name>-<in or out>-<index>
        # sendMessage: name of the method that sends the message
        # out: because is a consumer
        # 0: Index of the binding. This makes sense when the same method sends to multiple queues
        sendMessage-out-0:
          destination: ms-example-queue

server:
  # To avoid colliding with other apps in port 8080
  port: 8082


# App metadata
info:
  app:
    name: Producer example
    description: A producer example 
    version: 1.0.0
  company:
    name: MyCompany
    contact:
      email: support@mycompany.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}
