spring:
  application:
    # This should match the name used in config files
    name: candresborja-munozdjuan-nmontanez
  config:
    # Config server url
    import: configserver:http://localhost:8888
