spring:
application:
name: gateway
cloud:
gateway:
# Integration with eureka to discover all the routes
discovery:
locator:
enabled: true
lowerCaseServiceId: true
server:
port: 8080
# This is from the previous step
eureka:
client:
registerWithEureka: true
service-url:
defaultZone: ${EUREKA_SERVER_URL:http://localhost:9988/eureka/}
instance:
prefer-ip-address: true