server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        enabled: true
        # Repository from which the config files will be downloaded
        # Do not use this uri in production!
        # Instead, create a repo in a server and point to it using https
        # Remove this if using GIT to store config files
        native:
          search-locations:
          # The config files are stored in `src/main/resources/config`
          - classpath:/config
  profiles:
    active: native

eureka:
  client:
    # To report to Eureka when this service is up
    registerWithEureka: true
    # Eureka server URL
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9988/eureka/}
  instance:
    # To avoid using DNS
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# App metadata
info:
  app:
    name: Config Server
    description: A Config Server
    version: 1.0.0
